"""create patients and medical records tables

Revision ID: 3c9a6c24a2c1
Revises: e1bb89a5ff07
Create Date: 2026-03-08 02:06:20.431840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9a6c24a2c1'
down_revision: Union[str, Sequence[str], None] = 'e1bb89a5ff07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    op.create_table('medical_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('hba1c_baseline', sa.Float(), nullable=False),
    sa.Column('egfr', sa.Float(), nullable=False),
    sa.Column('diabetes_duration', sa.Float(), nullable=False),
    sa.Column('fasting_glucose', sa.Float(), nullable=False),
    sa.Column('c_peptide', sa.Float(), nullable=False),
    sa.Column('cvd', sa.Integer(), nullable=False),
    sa.Column('ckd', sa.Integer(), nullable=False),
    sa.Column('nafld', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Integer(), nullable=False),
    sa.Column('bp_systolic', sa.Float(), nullable=False),
    sa.Column('ldl', sa.Float(), nullable=False),
    sa.Column('hdl', sa.Float(), nullable=False),
    sa.Column('triglycerides', sa.Float(), nullable=False),
    sa.Column('alt', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_records_patient_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
