"""add simulations and simulation_steps tables

Revision ID: 818587a0958c
Revises: 29ddf149906c
Create Date: 2026-03-08 19:40:32.691956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818587a0958c'
down_revision: Union[str, Sequence[str], None] = '29ddf149906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('initial_epsilon', sa.Float(), nullable=False),
    sa.Column('epsilon_decay', sa.Float(), nullable=False),
    sa.Column('min_epsilon', sa.Float(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('reset_posterior', sa.Boolean(), nullable=False),
    sa.Column('dataset_filename', sa.String(length=255), nullable=False),
    sa.Column('dataset_row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='simulationstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('final_accuracy', sa.Float(), nullable=True),
    sa.Column('final_cumulative_reward', sa.Float(), nullable=True),
    sa.Column('final_cumulative_regret', sa.Float(), nullable=True),
    sa.Column('mean_reward', sa.Float(), nullable=True),
    sa.Column('mean_regret', sa.Float(), nullable=True),
    sa.Column('thompson_exploration_rate', sa.Float(), nullable=True),
    sa.Column('treatment_counts', sa.JSON(), nullable=True),
    sa.Column('confidence_distribution', sa.JSON(), nullable=True),
    sa.Column('safety_distribution', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_steps',
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('epsilon', sa.Float(), nullable=False),
    sa.Column('patient_context', sa.JSON(), nullable=False),
    sa.Column('oracle_rewards', sa.JSON(), nullable=False),
    sa.Column('optimal_treatment', sa.String(length=50), nullable=False),
    sa.Column('optimal_reward', sa.Float(), nullable=False),
    sa.Column('selected_treatment', sa.String(length=50), nullable=False),
    sa.Column('selected_idx', sa.Integer(), nullable=False),
    sa.Column('posterior_means', sa.JSON(), nullable=False),
    sa.Column('win_rates', sa.JSON(), nullable=False),
    sa.Column('confidence_pct', sa.Integer(), nullable=False),
    sa.Column('confidence_label', sa.String(length=20), nullable=False),
    sa.Column('sampled_values', sa.JSON(), nullable=False),
    sa.Column('runner_up', sa.String(length=50), nullable=False),
    sa.Column('runner_up_winrate', sa.Float(), nullable=False),
    sa.Column('mean_gap', sa.Float(), nullable=False),
    sa.Column('thompson_explored', sa.Boolean(), nullable=False),
    sa.Column('epsilon_explored', sa.Boolean(), nullable=False),
    sa.Column('posterior_mean_best', sa.String(length=50), nullable=False),
    sa.Column('observed_reward', sa.Float(), nullable=False),
    sa.Column('instantaneous_regret', sa.Float(), nullable=False),
    sa.Column('matched_oracle', sa.Boolean(), nullable=False),
    sa.Column('safety_status', sa.String(length=30), nullable=False),
    sa.Column('safety_contraindications', sa.JSON(), nullable=False),
    sa.Column('safety_warnings', sa.JSON(), nullable=False),
    sa.Column('cumulative_reward', sa.Float(), nullable=False),
    sa.Column('cumulative_regret', sa.Float(), nullable=False),
    sa.Column('running_accuracy', sa.Float(), nullable=False),
    sa.Column('treatment_counts', sa.JSON(), nullable=False),
    sa.Column('running_estimates', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_steps_simulation_id'), 'simulation_steps', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_steps_simulation_id'), table_name='simulation_steps')
    op.drop_table('simulation_steps')
    op.drop_table('simulations')
    # ### end Alembic commands ###
